name: Build and publish Docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${{ GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ GITHUB_REPOSITORY }}
        tag_with_ref: true
        tag_with_sha: true
